# Cloud build configuration to build a docker training image, submit it to the image registry, and run a training job
# https://cloud.google.com/build/docs/building/build-containers
# https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values 
# https://cloud.google.com/build/docs/build-config-file-schema
# https://cloud.google.com/sdk/gcloud/reference/ai/custom-jobs/create

substitutions:
  _IMAGE_NAME: "github.com/bieniekalexander/ml-model-promotion"
  _TAG_NAME: "${COMMIT_SHA}"
  _TRAINING_JOB_NAME: "${REPO_NAME}-${COMMIT_SHA}-build"
  _IMAGE_URI: "gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${_TAG_NAME}"
  _REGION: us-east1
timeout: 3600s
steps:
# build the docker image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "${_IMAGE_URI}", "."]

# if the docker image build is successful, submit it to the image registry
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "${_IMAGE_URI}"]

# run a training job using the docker image we just uploaded - https://cloud.google.com/sdk/gcloud/reference/ai/custom-jobs/create
- name: "gcr.io/cloud-builders/gcloud"
  args:
  - "ai"
  - "custom-jobs"
  - "create"
  - "--worker-pool-spec=executor-image-uri=${_IMAGE_URI},machine-type=n2-standard-4"
  - "--display-name=${_TRAINING_JOB_NAME}"  
  - "--region=${_REGION}"